CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pdf_excel_ai_config_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled INTEGER NOT NULL DEFAULT 0,
    base_url TEXT NOT NULL,
    model TEXT NOT NULL,
    timeout_seconds INTEGER NOT NULL,
    max_rows INTEGER NOT NULL,
    api_key_ciphertext TEXT NOT NULL DEFAULT '',
    repair_instruction TEXT NOT NULL DEFAULT '',
    rebuild_instruction TEXT NOT NULL DEFAULT '',
    header_mapping_instruction TEXT NOT NULL DEFAULT '',
    config_fingerprint TEXT NOT NULL,
    prompt_digest TEXT NOT NULL,
    test_status TEXT NOT NULL DEFAULT '',
    test_message TEXT NOT NULL DEFAULT '',
    tested_at TEXT,
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL,
    source_version_id BIGINT,
    activated_by TEXT NOT NULL DEFAULT '',
    activated_at TEXT NOT NULL DEFAULT '',
    FOREIGN KEY(source_version_id) REFERENCES pdf_excel_ai_config_versions(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS configuration_runtime_flags (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO configuration_runtime_flags(key,value)
VALUES ('capture_changes','false') ON CONFLICT(key) DO NOTHING;

CREATE TABLE IF NOT EXISTS configuration_change_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name TEXT NOT NULL,
    operation TEXT NOT NULL,
    pk_json JSONB NOT NULL,
    row_json JSONB,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    replayed_at TIMESTAMPTZ
);

CREATE OR REPLACE FUNCTION configuration_capture_change() RETURNS TRIGGER AS $$
DECLARE row_data JSONB; pk_data JSONB;
BEGIN
    IF COALESCE((SELECT value FROM configuration_runtime_flags WHERE key='capture_changes'),'false') <> 'true' THEN
        RETURN NULL;
    END IF;
    IF TG_OP='DELETE' THEN row_data := to_jsonb(OLD); ELSE row_data := to_jsonb(NEW); END IF;
    IF TG_TABLE_NAME='settings' THEN
        pk_data := jsonb_build_object('key',row_data -> 'key');
    ELSE
        pk_data := jsonb_build_object('id',row_data -> 'id');
    END IF;
    INSERT INTO configuration_change_log(table_name,operation,pk_json,row_json)
    VALUES (TG_TABLE_NAME,lower(TG_OP),pk_data,CASE WHEN TG_OP='DELETE' THEN NULL ELSE row_data END);
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS configuration_change_capture ON settings;
CREATE TRIGGER configuration_change_capture
AFTER INSERT OR UPDATE OR DELETE ON settings
FOR EACH ROW EXECUTE FUNCTION configuration_capture_change();
DROP TRIGGER IF EXISTS configuration_change_capture ON pdf_excel_ai_config_versions;
CREATE TRIGGER configuration_change_capture
AFTER INSERT OR UPDATE OR DELETE ON pdf_excel_ai_config_versions
FOR EACH ROW EXECUTE FUNCTION configuration_capture_change();
