CREATE TABLE IF NOT EXISTS automation_runtime_flags (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO automation_runtime_flags(key, value)
VALUES ('capture_changes', 'false')
ON CONFLICT(key) DO NOTHING;

CREATE TABLE IF NOT EXISTS automation_change_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_table TEXT NOT NULL,
    operation TEXT NOT NULL,
    pk_json JSONB NOT NULL,
    row_json JSONB,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    replayed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_automation_change_log_unreplayed
    ON automation_change_log(replayed_at, id);

CREATE OR REPLACE FUNCTION automation_capture_change() RETURNS TRIGGER AS $$
DECLARE
    row_data JSONB;
    key_data JSONB := '{}'::JSONB;
    key_name TEXT;
BEGIN
    IF COALESCE((SELECT value FROM automation_runtime_flags WHERE key='capture_changes'), 'false') <> 'true' THEN
        RETURN NULL;
    END IF;
    IF TG_OP = 'DELETE' THEN
        row_data := to_jsonb(OLD);
    ELSE
        row_data := to_jsonb(NEW);
    END IF;
    FOREACH key_name IN ARRAY TG_ARGV LOOP
        key_data := key_data || jsonb_build_object(key_name, row_data -> key_name);
    END LOOP;
    INSERT INTO automation_change_log(source_table, operation, pk_json, row_json)
    VALUES (TG_TABLE_NAME, lower(TG_OP), key_data, CASE WHEN TG_OP='DELETE' THEN NULL ELSE row_data END);
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
    item RECORD;
    trigger_name TEXT;
BEGIN
    FOR item IN
        SELECT * FROM (VALUES
            ('mail_accounts', ARRAY['id']), ('mail_messages', ARRAY['id']),
            ('mail_attachments', ARRAY['id']), ('mail_attachment_texts', ARRAY['attachment_id']),
            ('mail_fetch_logs', ARRAY['id']), ('mail_fetch_tasks', ARRAY['id']),
            ('mail_fetch_task_messages', ARRAY['fetch_task_id','mail_id']),
            ('mail_order_tasks', ARRAY['id']), ('mail_transcode_jobs', ARRAY['id']),
            ('order_intake_cases', ARRAY['id']), ('order_intake_case_events', ARRAY['id']),
            ('order_mail_routing_rules', ARRAY['id']), ('order_mail_routing_rule_events', ARRAY['id']),
            ('order_mail_rule_groups', ARRAY['id']), ('order_mail_rule_keywords', ARRAY['id']),
            ('order_change_tags', ARRAY['id']), ('order_change_tag_keywords', ARRAY['id']),
            ('order_entry_templates', ARRAY['id']), ('order_entry_template_lines', ARRAY['id']),
            ('order_entry_template_versions', ARRAY['id'])
        ) AS scoped(table_name, key_columns)
    LOOP
        trigger_name := 'automation_change_' || item.table_name;
        EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I', trigger_name, item.table_name);
        EXECUTE format(
            'CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON %I '
            'FOR EACH ROW EXECUTE FUNCTION automation_capture_change(%s)',
            trigger_name,
            item.table_name,
            (SELECT string_agg(quote_literal(column_name), ',') FROM unnest(item.key_columns) AS column_name)
        );
    END LOOP;
END;
$$;
