-- Keep first-time PDF/OCR extraction out of the browser request.  A task is
-- retained for each attempt so business users can see whether an attachment is
-- queued, being parsed, completed or needs a retry.
CREATE TABLE IF NOT EXISTS order_entry_template_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    employee_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    message TEXT NOT NULL DEFAULT '',
    template_id BIGINT,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    FOREIGN KEY(case_id) REFERENCES order_intake_cases(id),
    FOREIGN KEY(template_id) REFERENCES order_entry_templates(id)
);

CREATE INDEX IF NOT EXISTS idx_order_entry_template_tasks_case
    ON order_entry_template_tasks(case_id, employee_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_order_entry_template_tasks_status
    ON order_entry_template_tasks(status, started_at DESC);
