-- 接口维护、订单数据留痕和 Mock 调用记录。所有请求/响应只保存脱敏后的业务数据。
CREATE TABLE IF NOT EXISTS order_interface_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interface_key TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    enabled INTEGER NOT NULL DEFAULT 1,
    mode TEXT NOT NULL DEFAULT 'mock',
    method TEXT NOT NULL DEFAULT 'POST',
    base_url TEXT NOT NULL DEFAULT '',
    port INTEGER NOT NULL DEFAULT 443,
    path TEXT NOT NULL DEFAULT '',
    timeout_seconds INTEGER NOT NULL DEFAULT 8,
    request_mapping_json TEXT NOT NULL DEFAULT '{}',
    response_mapping_json TEXT NOT NULL DEFAULT '{}',
    mock_scenarios_json TEXT NOT NULL DEFAULT '{}',
    config_version INTEGER NOT NULL DEFAULT 1,
    created_by TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS order_interface_config_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interface_config_id BIGINT NOT NULL,
    config_version INTEGER NOT NULL,
    before_json TEXT NOT NULL DEFAULT '{}',
    after_json TEXT NOT NULL DEFAULT '{}',
    operated_by TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    FOREIGN KEY(interface_config_id) REFERENCES order_interface_configs(id)
);

CREATE TABLE IF NOT EXISTS order_entry_detail_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    template_id BIGINT,
    employee_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    title TEXT NOT NULL,
    detail_json TEXT NOT NULL DEFAULT '{}',
    operated_by TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    FOREIGN KEY(case_id) REFERENCES order_intake_cases(id),
    FOREIGN KEY(template_id) REFERENCES order_entry_templates(id)
);

CREATE TABLE IF NOT EXISTS order_interface_call_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    template_id BIGINT,
    employee_id TEXT NOT NULL,
    interface_config_id BIGINT,
    interface_key TEXT NOT NULL,
    config_version INTEGER NOT NULL DEFAULT 1,
    is_mock INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL,
    http_status INTEGER,
    duration_ms INTEGER,
    request_json TEXT NOT NULL DEFAULT '{}',
    response_json TEXT NOT NULL DEFAULT '{}',
    error_message TEXT NOT NULL DEFAULT '',
    triggered_by TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    FOREIGN KEY(case_id) REFERENCES order_intake_cases(id),
    FOREIGN KEY(template_id) REFERENCES order_entry_templates(id),
    FOREIGN KEY(interface_config_id) REFERENCES order_interface_configs(id)
);

CREATE TABLE IF NOT EXISTS order_material_query_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_log_id BIGINT NOT NULL,
    template_id BIGINT NOT NULL,
    line_no INTEGER NOT NULL,
    factory_part_no TEXT NOT NULL DEFAULT '',
    product_name TEXT NOT NULL DEFAULT '',
    matched_spec TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL,
    message TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    FOREIGN KEY(call_log_id) REFERENCES order_interface_call_logs(id),
    FOREIGN KEY(template_id) REFERENCES order_entry_templates(id)
);

CREATE INDEX IF NOT EXISTS idx_order_interface_call_logs_case
    ON order_interface_call_logs(case_id, employee_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_order_entry_detail_events_case
    ON order_entry_detail_events(case_id, employee_id, id DESC);
