-- Customer specification token positions maintained independently from the
-- customer master. Unmatched customer codes remain importable and visible.

CREATE TABLE IF NOT EXISTS automation_customer_spec_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code TEXT NOT NULL,
    customer_name TEXT NOT NULL DEFAULT '',
    product_type TEXT NOT NULL,
    delimiter TEXT NOT NULL DEFAULT '',
    glue_system_position INTEGER,
    thickness_position INTEGER,
    core_thickness_position INTEGER,
    dimension_position INTEGER,
    copper_foil_type_position INTEGER,
    copper_thickness_position INTEGER,
    structure_position INTEGER,
    watermark_position INTEGER,
    halogen_position INTEGER,
    rc_position INTEGER,
    cloth_type_position INTEGER,
    size_position INTEGER,
    note TEXT NOT NULL DEFAULT '',
    enabled INTEGER NOT NULL DEFAULT 1,
    source_json TEXT NOT NULL DEFAULT '{}',
    updated_by TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(customer_code, product_type),
    CHECK(product_type IN ('base', 'pp')),
    CHECK(enabled IN (0, 1)),
    CHECK(glue_system_position IS NULL OR glue_system_position BETWEEN 1 AND 99999),
    CHECK(thickness_position IS NULL OR thickness_position BETWEEN 1 AND 99999),
    CHECK(core_thickness_position IS NULL OR core_thickness_position BETWEEN 1 AND 99999),
    CHECK(dimension_position IS NULL OR dimension_position BETWEEN 1 AND 99999),
    CHECK(copper_foil_type_position IS NULL OR copper_foil_type_position BETWEEN 1 AND 99999),
    CHECK(copper_thickness_position IS NULL OR copper_thickness_position BETWEEN 1 AND 99999),
    CHECK(structure_position IS NULL OR structure_position BETWEEN 1 AND 99999),
    CHECK(watermark_position IS NULL OR watermark_position BETWEEN 1 AND 99999),
    CHECK(halogen_position IS NULL OR halogen_position BETWEEN 1 AND 99999),
    CHECK(rc_position IS NULL OR rc_position BETWEEN 1 AND 99999),
    CHECK(cloth_type_position IS NULL OR cloth_type_position BETWEEN 1 AND 99999),
    CHECK(size_position IS NULL OR size_position BETWEEN 1 AND 99999)
);

CREATE INDEX IF NOT EXISTS idx_customer_spec_mappings_lookup
    ON automation_customer_spec_mappings(customer_code, product_type, enabled);
CREATE INDEX IF NOT EXISTS idx_customer_spec_mappings_name
    ON automation_customer_spec_mappings(customer_name);
