-- 明细级料号查询、异步创建与回调闭环。
CREATE TABLE IF NOT EXISTS order_material_resolution_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    template_id BIGINT NOT NULL,
    employee_id TEXT NOT NULL,
    line_no INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    correlation_id TEXT NOT NULL UNIQUE,
    external_task_id TEXT NOT NULL DEFAULT '',
    input_json TEXT NOT NULL DEFAULT '{}',
    result_json TEXT NOT NULL DEFAULT '{}',
    last_call_log_id BIGINT,
    callback_received_at TEXT,
    resolved_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(template_id, line_no),
    FOREIGN KEY(case_id) REFERENCES order_intake_cases(id),
    FOREIGN KEY(template_id) REFERENCES order_entry_templates(id),
    FOREIGN KEY(last_call_log_id) REFERENCES order_interface_call_logs(id)
);

CREATE INDEX IF NOT EXISTS idx_order_material_resolution_callback
    ON order_material_resolution_tasks(correlation_id, status);
