-- Adhesive code master maintained from the ERP glue-system master workbook.

CREATE TABLE IF NOT EXISTS automation_adhesive_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adhesive_code TEXT NOT NULL UNIQUE,
    adhesive_name TEXT NOT NULL DEFAULT '',
    usage_category TEXT NOT NULL DEFAULT '',
    finance_category TEXT NOT NULL DEFAULT '',
    legacy_adhesive_code TEXT NOT NULL DEFAULT '',
    enabled INTEGER NOT NULL DEFAULT 1,
    source_json TEXT NOT NULL DEFAULT '{}',
    updated_by TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CHECK(enabled IN (0, 1))
);

CREATE INDEX IF NOT EXISTS idx_adhesive_codes_name
    ON automation_adhesive_codes(adhesive_name);
CREATE INDEX IF NOT EXISTS idx_adhesive_codes_categories
    ON automation_adhesive_codes(usage_category, finance_category, enabled);
