CREATE TABLE IF NOT EXISTS order_change_line_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    template_id BIGINT NOT NULL,
    employee_id TEXT NOT NULL,
    line_no INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'unqueried',
    match_level TEXT NOT NULL DEFAULT '',
    input_json TEXT NOT NULL DEFAULT '{}',
    candidates_json TEXT NOT NULL DEFAULT '[]',
    selected_candidate_json TEXT NOT NULL DEFAULT '{}',
    query_call_log_id BIGINT,
    selected_by TEXT NOT NULL DEFAULT '',
    selected_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(template_id, line_no),
    FOREIGN KEY(case_id) REFERENCES order_intake_cases(id),
    FOREIGN KEY(template_id) REFERENCES order_entry_templates(id),
    FOREIGN KEY(query_call_log_id) REFERENCES order_interface_call_logs(id)
);

CREATE INDEX IF NOT EXISTS idx_order_change_line_matches_case
    ON order_change_line_matches(case_id, employee_id, line_no);
