CREATE TABLE IF NOT EXISTS order_entry_template_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL,
    group_key TEXT NOT NULL,
    order_number TEXT NOT NULL DEFAULT '',
    header_json TEXT NOT NULL DEFAULT '{}',
    sort_order INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'pending',
    nyeos_order_number TEXT NOT NULL DEFAULT '',
    erp_order_number TEXT NOT NULL DEFAULT '',
    submitted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(template_id, group_key),
    FOREIGN KEY(template_id) REFERENCES order_entry_templates(id)
);

ALTER TABLE order_entry_template_lines
    ADD COLUMN IF NOT EXISTS group_id BIGINT REFERENCES order_entry_template_groups(id);
ALTER TABLE order_interface_call_logs
    ADD COLUMN IF NOT EXISTS order_group_id BIGINT REFERENCES order_entry_template_groups(id);

CREATE INDEX IF NOT EXISTS idx_order_entry_groups_template
    ON order_entry_template_groups(template_id, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_order_entry_lines_group
    ON order_entry_template_lines(group_id, line_no);
CREATE INDEX IF NOT EXISTS idx_order_interface_logs_group
    ON order_interface_call_logs(order_group_id, id DESC);

INSERT INTO order_entry_template_groups(
    template_id, group_key, order_number, header_json, sort_order, status,
    nyeos_order_number, erp_order_number, submitted_at, created_at, updated_at
)
SELECT
    template.id, 'legacy-' || template.id,
    COALESCE(NULLIF(template.header_json::jsonb ->> 'customer_order_number', ''), ''),
    template.header_json, 0,
    CASE WHEN EXISTS (
        SELECT 1 FROM order_interface_call_logs call
        WHERE call.template_id=template.id
          AND call.interface_key='domestic_order_entry' AND call.status='success'
    ) THEN 'submitted' ELSE 'pending' END,
    '', '',
    CASE WHEN EXISTS (
        SELECT 1 FROM order_interface_call_logs call
        WHERE call.template_id=template.id
          AND call.interface_key='domestic_order_entry' AND call.status='success'
    ) THEN template.updated_at ELSE NULL END,
    template.created_at, template.updated_at
FROM order_entry_templates template
WHERE NOT EXISTS (
    SELECT 1 FROM order_entry_template_groups existing
    WHERE existing.template_id=template.id
);

UPDATE order_entry_template_lines line
SET group_id=groups.id
FROM order_entry_template_groups groups
WHERE line.template_id=groups.template_id AND line.group_id IS NULL;

UPDATE order_interface_call_logs call
SET order_group_id=groups.id
FROM order_entry_template_groups groups
WHERE call.template_id=groups.template_id
  AND call.order_group_id IS NULL
  AND call.interface_key='domestic_order_entry';
