CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature TEXT NOT NULL DEFAULT 'fangzheng', employee_id TEXT NOT NULL,
    source_filename TEXT NOT NULL, stored_input_path TEXT NOT NULL, stored_result_path TEXT,
    status TEXT NOT NULL, success_count INTEGER NOT NULL DEFAULT 0,
    fail_count INTEGER NOT NULL DEFAULT 0, skip_count INTEGER NOT NULL DEFAULT 0,
    current_row INTEGER NOT NULL DEFAULT 0, total_rows INTEGER NOT NULL DEFAULT 0,
    worker_pid INTEGER, worker_started_at TEXT, rule_version TEXT NOT NULL,
    log_text TEXT NOT NULL DEFAULT '', error_message TEXT, created_at TEXT NOT NULL,
    completed_at TEXT, confirm_count INTEGER NOT NULL DEFAULT 0, verify_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pp_transcode_base_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, field_key TEXT NOT NULL,
    input_value TEXT NOT NULL, output_value TEXT NOT NULL, business_note TEXT NOT NULL DEFAULT '',
    enabled INTEGER NOT NULL DEFAULT 1, source_kind TEXT NOT NULL DEFAULT 'page',
    created_by TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL,
    updated_by TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL,
    UNIQUE(field_key, input_value)
);
CREATE TABLE IF NOT EXISTS pp_transcode_customer_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_code TEXT NOT NULL DEFAULT '',
    customer_name TEXT NOT NULL DEFAULT '', target_field TEXT NOT NULL,
    conditions_json TEXT NOT NULL DEFAULT '[]', output_value TEXT NOT NULL,
    business_note TEXT NOT NULL DEFAULT '', enabled INTEGER NOT NULL DEFAULT 1,
    created_by TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL,
    updated_by TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS pp_transcode_rule_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, rule_scope TEXT NOT NULL,
    rule_id BIGINT, action TEXT NOT NULL, before_json TEXT NOT NULL DEFAULT '{}',
    after_json TEXT NOT NULL DEFAULT '{}', changed_by TEXT NOT NULL DEFAULT '', changed_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS pp_transcode_confirmation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_id BIGINT NOT NULL,
    employee_id TEXT NOT NULL, excel_row INTEGER NOT NULL, customer_code TEXT NOT NULL DEFAULT '',
    customer_name TEXT NOT NULL DEFAULT '', spec TEXT NOT NULL, order_remark TEXT NOT NULL DEFAULT '',
    pending_code TEXT NOT NULL DEFAULT '', confirmed_pending_code TEXT NOT NULL DEFAULT '',
    confidence INTEGER NOT NULL DEFAULT 0, summary TEXT NOT NULL DEFAULT '',
    field_evidence_json TEXT NOT NULL DEFAULT '[]', confirmation_status TEXT NOT NULL DEFAULT 'pending',
    confirmation_basis TEXT NOT NULL DEFAULT '', confirmed_by TEXT NOT NULL DEFAULT '',
    confirmed_at TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
    UNIQUE(job_id, excel_row), FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS transcode_model_configs (
    employee_id TEXT PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 0,
    base_url TEXT NOT NULL DEFAULT 'https://api.deepseek.com', api_key TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT 'deepseek-v4-pro', timeout_seconds DOUBLE PRECISION NOT NULL DEFAULT 60,
    max_order_calls INTEGER NOT NULL DEFAULT 50, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS transcode_agent_confirmation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_id BIGINT NOT NULL,
    employee_id TEXT NOT NULL, excel_row INTEGER NOT NULL, customer_code TEXT NOT NULL DEFAULT '',
    customer_name TEXT NOT NULL DEFAULT '', spec TEXT NOT NULL DEFAULT '', context_text TEXT NOT NULL DEFAULT '',
    field_key TEXT NOT NULL, field_label TEXT NOT NULL, current_code TEXT NOT NULL DEFAULT '',
    options_json TEXT NOT NULL DEFAULT '[]', pending_code TEXT NOT NULL DEFAULT '', score INTEGER NOT NULL DEFAULT 0,
    reason TEXT NOT NULL DEFAULT '', evidence_json TEXT NOT NULL DEFAULT '{}', analysis_json TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'pending', confirmed_code TEXT, confirmation_basis TEXT,
    confirmed_by TEXT, confirmed_at TEXT, long_term_rule_id TEXT, created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL, pending_rule_id TEXT, UNIQUE(job_id, excel_row, field_key),
    FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS transcode_agent_confirmation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, item_id BIGINT,
    job_id BIGINT NOT NULL, employee_id TEXT NOT NULL, action TEXT NOT NULL,
    before_json TEXT NOT NULL DEFAULT '{}', after_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL,
    FOREIGN KEY(item_id) REFERENCES transcode_agent_confirmation_items(id) ON DELETE SET NULL,
    FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS transcode_agent_pending_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, rule_id TEXT NOT NULL,
    rule_json TEXT NOT NULL, employee_id TEXT NOT NULL, customer_code TEXT NOT NULL DEFAULT '',
    customer_name TEXT NOT NULL DEFAULT '', business_field TEXT NOT NULL DEFAULT '',
    target_value TEXT NOT NULL DEFAULT '', condition_summary TEXT NOT NULL DEFAULT '',
    source_task_id BIGINT, source_excel_row INTEGER, status TEXT NOT NULL DEFAULT 'pending',
    created_at TEXT NOT NULL, updated_at TEXT NOT NULL, updated_by TEXT NOT NULL DEFAULT '',
    processed_by TEXT NOT NULL DEFAULT '', processed_at TEXT
);
CREATE TABLE IF NOT EXISTS transcode_agent_row_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_id BIGINT NOT NULL,
    excel_row INTEGER NOT NULL, employee_id TEXT NOT NULL, action TEXT NOT NULL,
    before_code TEXT NOT NULL DEFAULT '', after_code TEXT NOT NULL DEFAULT '', basis TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL, UNIQUE(job_id, excel_row),
    FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS transcode_agent_rule_overrides (
    rule_id TEXT PRIMARY KEY, rule_json TEXT, deleted INTEGER NOT NULL DEFAULT 0,
    updated_by TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS transcode_customer_rule_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, rule_id TEXT NOT NULL,
    action TEXT NOT NULL, employee_id TEXT NOT NULL, before_json TEXT, after_json TEXT, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS transcode_customer_rule_overrides (
    rule_id TEXT PRIMARY KEY, rule_json TEXT, deleted INTEGER NOT NULL DEFAULT 0,
    updated_by TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS transcode_rule_center_asset_overrides (
    asset_group TEXT NOT NULL, row_id TEXT NOT NULL, row_json TEXT,
    deleted INTEGER NOT NULL DEFAULT 0, updated_by TEXT NOT NULL, updated_at TEXT NOT NULL,
    PRIMARY KEY(asset_group, row_id)
);
CREATE TABLE IF NOT EXISTS transcode_rule_center_base_overrides (
    rule_id TEXT PRIMARY KEY, rule_json TEXT, deleted INTEGER NOT NULL DEFAULT 0,
    updated_by TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS transcode_rule_center_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category TEXT NOT NULL,
    object_id TEXT NOT NULL, action TEXT NOT NULL, employee_id TEXT NOT NULL,
    before_json TEXT, after_json TEXT, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS transcode_rule_center_confirmation_overrides (
    rule_id TEXT PRIMARY KEY, rule_json TEXT, deleted INTEGER NOT NULL DEFAULT 0,
    updated_by TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS transcode_rule_center_lookup_overrides (
    group_key TEXT NOT NULL, input_value TEXT NOT NULL, output_value TEXT,
    deleted INTEGER NOT NULL DEFAULT 0, updated_by TEXT NOT NULL, updated_at TEXT NOT NULL,
    PRIMARY KEY(group_key, input_value)
);

CREATE INDEX IF NOT EXISTS idx_jobs_employee_feature ON jobs(employee_id, feature, id DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_status_created ON jobs(status, created_at);
CREATE INDEX IF NOT EXISTS idx_transcode_agent_confirm_job_status ON transcode_agent_confirmation_items(job_id, status, excel_row);
CREATE INDEX IF NOT EXISTS idx_transcode_agent_confirm_owner ON transcode_agent_confirmation_items(employee_id, job_id);
CREATE INDEX IF NOT EXISTS idx_transcode_agent_pending_rules_status ON transcode_agent_pending_rules(status, employee_id);
CREATE INDEX IF NOT EXISTS idx_transcode_customer_rule_changes_rule ON transcode_customer_rule_changes(rule_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_transcode_rule_center_changes ON transcode_rule_center_changes(category, object_id, id DESC);

CREATE TABLE IF NOT EXISTS transcode_runtime_flags (
    key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO transcode_runtime_flags(key,value) VALUES ('capture_changes','false') ON CONFLICT(key) DO NOTHING;
CREATE TABLE IF NOT EXISTS transcode_change_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, table_name TEXT NOT NULL,
    operation TEXT NOT NULL, pk_json JSONB NOT NULL, row_json JSONB,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, replayed_at TIMESTAMPTZ
);
CREATE OR REPLACE FUNCTION transcode_capture_change() RETURNS TRIGGER AS $$
DECLARE row_data JSONB; pk_data JSONB := '{}'::jsonb; key_name TEXT;
BEGIN
    IF COALESCE((SELECT value FROM transcode_runtime_flags WHERE key='capture_changes'),'false') <> 'true' THEN
        RETURN NULL;
    END IF;
    IF TG_OP='DELETE' THEN row_data := to_jsonb(OLD); ELSE row_data := to_jsonb(NEW); END IF;
    FOREACH key_name IN ARRAY TG_ARGV LOOP
        pk_data := pk_data || jsonb_build_object(key_name, row_data -> key_name);
    END LOOP;
    INSERT INTO transcode_change_log(table_name,operation,pk_json,row_json)
    VALUES (TG_TABLE_NAME,lower(TG_OP),pk_data,CASE WHEN TG_OP='DELETE' THEN NULL ELSE row_data END);
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE item RECORD;
BEGIN
    FOR item IN SELECT * FROM (VALUES
        ('jobs',ARRAY['id']),('pp_transcode_base_rules',ARRAY['id']),('pp_transcode_customer_rules',ARRAY['id']),
        ('pp_transcode_rule_changes',ARRAY['id']),('pp_transcode_confirmation_items',ARRAY['id']),
        ('transcode_model_configs',ARRAY['employee_id']),('transcode_agent_confirmation_items',ARRAY['id']),
        ('transcode_agent_confirmation_events',ARRAY['id']),('transcode_agent_pending_rules',ARRAY['id']),
        ('transcode_agent_row_verifications',ARRAY['id']),('transcode_agent_rule_overrides',ARRAY['rule_id']),
        ('transcode_customer_rule_changes',ARRAY['id']),('transcode_customer_rule_overrides',ARRAY['rule_id']),
        ('transcode_rule_center_asset_overrides',ARRAY['asset_group','row_id']),
        ('transcode_rule_center_base_overrides',ARRAY['rule_id']),('transcode_rule_center_changes',ARRAY['id']),
        ('transcode_rule_center_confirmation_overrides',ARRAY['rule_id']),
        ('transcode_rule_center_lookup_overrides',ARRAY['group_key','input_value'])
    ) AS scoped(table_name,pk_columns)
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS transcode_change_capture ON %I',item.table_name);
        EXECUTE format(
            'CREATE TRIGGER transcode_change_capture AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION transcode_capture_change(%s)',
            item.table_name,
            (SELECT string_agg(quote_literal(value),',') FROM unnest(item.pk_columns) AS value)
        );
    END LOOP;
END $$;
