CREATE TABLE IF NOT EXISTS users (
    employee_id TEXT PRIMARY KEY,
    display_name TEXT,
    department TEXT,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    enabled INTEGER NOT NULL DEFAULT 1,
    must_change_password INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS identity_runtime_flags (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO identity_runtime_flags(key, value)
VALUES ('capture_changes', 'false')
ON CONFLICT(key) DO NOTHING;

CREATE TABLE IF NOT EXISTS identity_change_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    row_json JSONB,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    replayed_at TIMESTAMPTZ
);

CREATE OR REPLACE FUNCTION identity_capture_user_change() RETURNS TRIGGER AS $$
DECLARE
    row_data JSONB;
BEGIN
    IF COALESCE((SELECT value FROM identity_runtime_flags WHERE key='capture_changes'), 'false') <> 'true' THEN
        RETURN NULL;
    END IF;
    IF TG_OP = 'DELETE' THEN
        row_data := to_jsonb(OLD);
    ELSE
        row_data := to_jsonb(NEW);
    END IF;
    INSERT INTO identity_change_log(operation, employee_id, row_json)
    VALUES (lower(TG_OP), row_data ->> 'employee_id', CASE WHEN TG_OP='DELETE' THEN NULL ELSE row_data END);
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS identity_change_users ON users;
CREATE TRIGGER identity_change_users
AFTER INSERT OR UPDATE OR DELETE ON users
FOR EACH ROW EXECUTE FUNCTION identity_capture_user_change();
