CREATE TABLE IF NOT EXISTS task_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id TEXT NOT NULL,
    name TEXT NOT NULL,
    short_label TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(employee_id, name)
);

CREATE TABLE IF NOT EXISTS personal_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id TEXT NOT NULL,
    category_id BIGINT,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    task_tag TEXT NOT NULL DEFAULT '',
    priority TEXT NOT NULL DEFAULT 'normal',
    progress TEXT NOT NULL DEFAULT 'not_started',
    due_date TEXT,
    archived_at TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    priority_sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(category_id) REFERENCES task_categories(id)
);

CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id TEXT NOT NULL,
    feedback_type TEXT NOT NULL,
    feature TEXT,
    material_desc TEXT,
    system_result TEXT,
    expected_result TEXT,
    content TEXT,
    daily_workload TEXT,
    error_probability TEXT,
    urgency TEXT,
    status TEXT NOT NULL DEFAULT '待处理',
    admin_note TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_task_categories_employee_sort
ON task_categories(employee_id, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_personal_tasks_employee_active
ON personal_tasks(employee_id, archived_at, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_feedback_employee_type
ON feedback(employee_id, feedback_type, id DESC);

CREATE TABLE IF NOT EXISTS planning_runtime_flags (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO planning_runtime_flags(key,value)
VALUES ('capture_changes','false') ON CONFLICT(key) DO NOTHING;

CREATE TABLE IF NOT EXISTS planning_change_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name TEXT NOT NULL,
    operation TEXT NOT NULL,
    pk_json JSONB NOT NULL,
    row_json JSONB,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    replayed_at TIMESTAMPTZ
);

CREATE OR REPLACE FUNCTION planning_capture_change() RETURNS TRIGGER AS $$
DECLARE row_data JSONB; pk_data JSONB;
BEGIN
    IF COALESCE((SELECT value FROM planning_runtime_flags WHERE key='capture_changes'),'false') <> 'true' THEN
        RETURN NULL;
    END IF;
    IF TG_OP='DELETE' THEN row_data := to_jsonb(OLD); ELSE row_data := to_jsonb(NEW); END IF;
    pk_data := jsonb_build_object('id',row_data -> 'id');
    INSERT INTO planning_change_log(table_name,operation,pk_json,row_json)
    VALUES (TG_TABLE_NAME,lower(TG_OP),pk_data,CASE WHEN TG_OP='DELETE' THEN NULL ELSE row_data END);
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS planning_change_capture ON task_categories;
CREATE TRIGGER planning_change_capture AFTER INSERT OR UPDATE OR DELETE ON task_categories
FOR EACH ROW EXECUTE FUNCTION planning_capture_change();
DROP TRIGGER IF EXISTS planning_change_capture ON personal_tasks;
CREATE TRIGGER planning_change_capture AFTER INSERT OR UPDATE OR DELETE ON personal_tasks
FOR EACH ROW EXECUTE FUNCTION planning_capture_change();
DROP TRIGGER IF EXISTS planning_change_capture ON feedback;
CREATE TRIGGER planning_change_capture AFTER INSERT OR UPDATE OR DELETE ON feedback
FOR EACH ROW EXECUTE FUNCTION planning_capture_change();
