from __future__ import annotations

from pathlib import Path
from typing import BinaryIO, Mapping, Protocol


class FileStorage(Protocol):
    def save(self, stream: BinaryIO, object_key: str, metadata: Mapping[str, str] | None = None) -> Path: ...

    def open(self, *, object_key: str = "", legacy_path: str = "") -> BinaryIO: ...

    def resolve(self, *, object_key: str = "", legacy_path: str = "") -> Path: ...

    def exists(self, *, object_key: str = "", legacy_path: str = "") -> bool: ...

    def checksum(self, *, object_key: str = "", legacy_path: str = "") -> str: ...

    def delete(self, object_key: str) -> None: ...

    def temporary_download_url(self, object_key: str, expires_seconds: int = 300) -> str | None: ...
